-- Assertions that verify.sql reports a clean state once the statements
-- generated by remediate.sql have actually been run. This is the third leg
-- of the loop: find (audit.sql), fix (remediate.sql), confirm (verify.sql).
-- Run after fixture.sql and after executing remediate.sql's output.

begin;

-- psql cannot finish an open statement from inside \i, so the shipped
-- file is read into a variable and interpolated whole.
\set verify_query `cat sql/verify.sql`
create temporary table verify_results as :verify_query

do $$
declare
  r record;
begin
  select * into r from verify_results;

  if r.tables_without_rls <> 0 then
    raise exception 'expected 0 tables_without_rls after remediation, got %', r.tables_without_rls;
  end if;

  if r.anon_callable_secdef <> 0 then
    raise exception 'expected 0 anon_callable_secdef after remediation, got %', r.anon_callable_secdef;
  end if;

  if r.unpinned_search_path <> 0 then
    raise exception 'expected 0 unpinned_search_path after remediation, got %', r.unpinned_search_path;
  end if;

  if r.trigger_fns_callable <> 0 then
    raise exception 'expected 0 trigger_fns_callable after remediation, got %', r.trigger_fns_callable;
  end if;

  -- These two are supposed to stay non-zero: they are the real API surface
  -- and the tables that now correctly deny by default.
  if r.authenticated_api_fns <= 0 then
    raise exception 'expected authenticated_api_fns to stay non-zero, got %', r.authenticated_api_fns;
  end if;

  if r.tables_with_rls <= 0 then
    raise exception 'expected tables_with_rls to stay non-zero, got %', r.tables_with_rls;
  end if;

  raise notice 'verify.sql reports a clean state after remediation';
end $$;

rollback;
